interface ExportCluster {
  title: string;
  summary: string;
  frameName: string;
  priority: string;
  status: string;
  effortEstimate: string | null;
  comments: { authorName: string; message: string; createdAt: string }[];
}

export function toMarkdown(
  projectName: string,
  roundName: string,
  executiveSummary: string | null,
  clusters: ExportCluster[]
): string {
  let md = `# ${projectName} - ${roundName}\n\n`;
  md += `*Generated by FigBack on ${new Date().toLocaleDateString()}*\n\n`;

  if (executiveSummary) {
    md += `## Executive Summary\n\n${executiveSummary}\n\n`;
  }

  md += `## Issues (${clusters.length})\n\n`;

  for (const cluster of clusters) {
    md += `### ${cluster.title}\n\n`;
    md += `**Frame:** ${cluster.frameName} | **Priority:** ${cluster.priority} | **Status:** ${cluster.status}`;
    if (cluster.effortEstimate) md += ` | **Effort:** ${cluster.effortEstimate}`;
    md += `\n\n`;
    md += `${cluster.summary}\n\n`;

    if (cluster.comments.length > 0) {
      md += `**Comments:**\n\n`;
      for (const c of cluster.comments) {
        md += `- **${c.authorName}** (${new Date(c.createdAt).toLocaleDateString()}): ${c.message}\n`;
      }
      md += `\n`;
    }

    md += `---\n\n`;
  }

  return md;
}

export function toCsv(clusters: ExportCluster[]): string {
  const headers = [
    "Title",
    "Summary",
    "Frame",
    "Priority",
    "Status",
    "Effort",
    "Comment Count",
  ];

  const rows = clusters.map((c) => [
    csvEscape(c.title),
    csvEscape(c.summary),
    csvEscape(c.frameName),
    c.priority,
    c.status,
    c.effortEstimate ?? "",
    String(c.comments.length),
  ]);

  return [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
}

function csvEscape(s: string): string {
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}
